### ISSUE TITLE
how to avoid short names?

### ISSUE THREAD

**Issue by PavelPolyakov** [bucaran/parsec#5]
Hi,

Assuming I'm trying to parse the next expression:
```
DEBUG=* node --harmony --expose-gc  app.js --domain=domain_name
```

With this configuration:
```javascript
var r = Parsec.parse(process.argv).options('domain',{default:defaultDomain}).
                options('env',{default:defaultEnv});
```

As result, I get the next:
```
{ domain: 'default_domain',
  options: [Function],
  d: 'default_domain',
  env: 'local',
  e: 'local' }
```

I do not want the short keys to be present there. How can I avoid it?
btw, I do not want the ```options``` key to be present there as well, but it's not so important.

Regards,

**Comment by PavelPolyakov** [comment]
Looks like this approach would help:
```javascript
var parsecObject = Parsec.parse(process.argv)
                .options(['domain'], {default: defaultDomain}).
                options(['env'], {default: defaultEnv});
```

**Comment by bucaran** [comment]
##### 1

```js
DEBUG="*" node --harmony --expose-gc  examples/index.js --domain=domain_name 
```

Result:

```json
{ 
  domain: 'domain_name',
  options: [Function],
  d: 'domain_name',
  env: 'defaultEnv',
  e: 'defaultEnv' 
}
```

> I do not want the short keys to be present there. How can I avoid it?

Right. You don't need the short keys, because you want to always use the more readable long option version if there is one. This however is usually irrelevant, because the long option is there anyway, so I don't see how the short option could be interfering with your use case. I can't just force remove the short options, because there could be a use case for them as well. As you probably noticed already, the default behavior is => `"string"` injects `s` and `string` in the returned object. 

If you want to get only the long option, you can pass an array like you yourself suggested. Another idea could be to add an option to parse, for example:

`Parsec.parse(process.argv, {  shortLess: true })...`

##### 2

> I do not want the options key to be present there as well, but it's not so important.

I see what you mean. This one was a tough call for me too, but without this `Parsec` would be too limited IMO. I don't think there is a straightforward way to purge `options` since the options method returns an object with an `options` method itself. Perhaps, making options appear first and having `parse` come at the end could be an alternative, but the composition would change significantly.

```js
Parsec
  .options("")
  .options("")
  .parse(process.argv)
```

Not a big deal really and it should not be too hard to implement. This way we could get rid of `options` without trouble.

**Comment by PavelPolyakov** [comment]
Thanks for the answers.

I think the shortname issue should be optional, because for me the shortname from my longname has no logic, because at the beggining I've "ordered" only to parse the longname one :)

Indeed all of my issues were solved for now. Thanks for the library.

The options was solved like (using https://lodash.com/):
```javascript
this.cliConfig = _.omit(parsec,'options');
```

Regards,

**Comment by bucaran** [comment]
I see what you mean now.

It's very common to have the short option as the first letter of the long option, hence the current behavior. For extraordinary use cases, the solution is still pretty simple, `.options(["option"])`.

If I change the composition to

```js
Parsec
  .options("")
  .options("")
  .parse(process.argv)
```

we don't need `lodash` only for this, but can I ask you one thing, why do you need to omit the `options` property? Are you perhaps handling an option named `options` in your program?

**Comment by bucaran** [comment]
Closing this.

@PavelPolyakov Feel free to post your comments anytime. :+1:
